name: Deployment

on:
  push:
    branches: ["main"]

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          yarn
          yarn zip
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.zip

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: TryGhost/action-deploy-theme@v1.4.1
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
